export const CLIENT_STATUSES = [
  'Cancelled',
  'Complete',
  'Complete Sent',
  'In Process',
  'Invisible',
  'New',
  'New - Incomplete',
  'Scheduled',
  'Update',
  'Urgent'
]

export const OPERATION_STATUSES = [
  'Deleted',
  'Last min Cancellation'
]

export const QA_STATUSES = [
  'Deck QA',
  'Participant Calendar QA',
  'Presenter Calendar QA',
  'QA 1',
  'QA 2',
  'SOD'
]

export const PRODUCTION_STATUSES = [
  'Producer Assigned',
  'Report Sent',
  'Unassigned',
  'Producer Declined',
  'Report Created'
]

export const PEOPLE_ASSIGNED_ROLES = [
  'Client Contact 1',
  'Client Contact 2',
  'Client Contact 3',
  'Coordinator',
  'Extra Producer 1',
  'Extra Producer 2',
  'Extra Producer 3',
  'Extra Producer 4',
  'Extra Producer 5',
  'Extra Producer 6',
  'Extra Producer 7',
  'Extra Producer 8',
  'Extra Producer 9',
  'Helpdesk 1',
  'Helpdesk 2',
  'Helpdesk 3',
  'Helpdesk 4',
  'Onsite Producer 1',
  'Onsite Producer 2',
  'Project Manager 1',
  'Project Manager 2',
  'Remote Producer 1',
  'Remote Producer 2',
  'Shadow Producer 1',
  'Shadow Producer 2',
  'Shadow Producer 3',
  'Shadow Producer 4'
]

export const PRODUCT_ITEMS = [
  'AC Config',
  'Analytics',
  'Audio Configuration',
  'Breakouts',
  'Design Session',
  'Duration',
  'e-mail Campaign',
  'Event Package',
  'Event Settings',
  'Extra Producer',
  'Onsite Producer',
  'Participant count',
  'Pop up studio',
  'Presenter count',
  'Project Management',
  'Recording',
  'Recording output',
  'Rehearsal',
  'Remote Producer',
  'Report Format',
  'Room Type',
  'Tech check'
]

export const CLIENT_ITEMS = [
  'Administrative contact',
  'Audio',
  'Client ',
  'Client Contact Email',
  'Client Contact Phone',
  'Client ID',
  'Event Documents contact 1',
  'Event Documents contact 2',
  'Event Documents contact 3',
  'Event Name',
  'Event Type',
  'Financial Contact 1',
  'Meeting ID',
  'Participant Communication',
  'Project Name',
  'Report Recipient',
  'Report Recipient 1',
  'Speaker Communication',
  'Technical contact',
  'TO/PO'
]

export const CHECKLIST_ITEMS = [
  'Ambassador Email',
  'Ambassador Name',
  'Ambassador Phone',
  'Audio License',
  'Audio Name',
  'Audio Type',
  'Biogen Rep Email',
  'Biogen Rep Name',
  'Biogen Rep Phone',
  'Biogen Rep Photo',
  'Deck',
  'Deck link',
  'Event Documents',
  'Event End Time',
  'Event Start Time',
  'Field Rep Email',
  'Field Rep Name',
  'Field Rep Phone',
  'Global Link',
  'HCP Speaker Email',
  'HCP Speaker Name',
  'HCP Speaker Phone',
  'HCP Speaker Photo',
  'Host Code',
  'Meeting Link',
  'Meeting Link Owner',
  'Meeting Password',
  'Meeting Portal',
  'Meeting Username',
  'Participant Calendar',
  'Participant Code',
  'Patient Speaker Email',
  'Patient Speaker Name',
  'Patient Speaker Phone',
  'Patient Speaker Photo',
  'Presenter 1 Email',
  'Presenter 1 Name',
  'Presenter Calendar',
  'Producer Calendar',
  'Recording',
  'Rehearsal Date',
  'Rehearsal Time',
  'Remote Pareticipant Email 1',
  'Remote Pareticipant Email 2',
  'Remote Participant Name 1',
  'Remote Participant Name 2',
  'Report Delivery Method',
  'Report Link',
  'Report Sent',
  'Room Type',
  'Run Sheet',
  'Site Address',
  'Speaker Bio',
  'Speaker Bio Link',
  'Support Type',
  'Tech check Date',
  'Tech check Time',
  'Teleconference #',
  'TLL/KAM Email',
  'TLL/KAM Name',
  'TLL/KAM Phone',
  'TLL/KCM Email',
  'TLL/KCM Name',
  'TLL/KCM Phone',
  'Video',
  'Video Link',
  'Webcam'
]

export const EMAIL_PROCESS_TYPES = {
  scheduled: 'scheduled',
  external_notes: 'external_notes'
};
