export class EventObject {
  client_id;
  client_status;
  duration_minutes;
  event_code;
  event_id;
  event_name;
  event_start;
  external_notes;
  internal_notes;
  operations_status;
  producer_count;
  producer_notes;
  producer_offset_minutes;
  production_status;
  project_id;
  qa_status;
  time_zone;
  send_email;
  email_external_notes;
}
